const translations = {
  en: {
   // top bar
    time: "10:00 am - 5:00 pm",
    "opening hours": "Opening Hour: Sunday - Friday",
    number: "+977 12346789",
    "number description": "Call Us For Consultation",
    // navbar
    home: "Home",
    about: "About",
    practice: "Practice",
    attorneys: "Attorneys",
    contact: "Contact",
    location: "Location",
    // carousel
    carousel1: "We fight for your justice",
    "carousel1 desc": "Justice stands as the foundation of a fair society, ensuring every individual receives equal protection, dignity, and accountability under the rule of law.",
    carousel2: "We prepared to oppose for you",
    "carousel2 desc": "Our team is committed to defending your rights with determination, strategic advocacy, and unwavering dedication to achieving the best possible outcome.",
    carousel3: "We fight for your privilege",
    "carousel3 desc": "We stand firmly to protect your legal interests, advocating for your rights with integrity, expertise, and a strong commitment to justice.",
    //top feature
    feature1: "Legal",
    "feature1 desc": "Government Approved",
    feature2: "Attorneys",
    "feature2 desc": "Expert Attorneys",
    feature3: "Success",
    "feature3 desc": "High Win Rate",
    feature4: "Support",
    "feature4 desc": "Quick Support",
    //about
    a1: "Learn About Us",
    "a1 desc1": "The Environment Law Society Nepal (ELS Nepal) comprises a dedicated group of seven legal professionals practicing as advocates and consultant lawyers across a broad spectrum of legal fields, including civil law, family law, education law, business law, and criminal law. While each member maintains an independent legal practice, they are collectively united under the platform of ELS Nepal with the shared objective of promoting, advocating for, and strengthening the implementation of environmental law in Nepal.",
    "a1 desc2": "Our collective mission is to safeguard environmental justice while also providing comprehensive legal support to individuals and organizations. Clients may approach us for professional legal representation and consultation on personal legal matters, where our advocates provide diligent and principled assistance grounded in legal expertise and ethical practice. Beyond legal services, the Environment Law Society Nepal actively welcomes collaboration with legal professionals, conservationists, researchers, and international partners who share a commitment to environmental protection and sustainable development.",
    "a1 desc3": "Learn More",
    //service
    s: "Our Practice Areas",
    s1: "Environment Law",
    "s1 desc": "We provide legal expertise in environmental law, assisting clients with regulatory compliance, environmental impact assessments, and advocacy for sustainable practices to protect our planet for future generations.",
    s2: "Civil Law",
    "s2 desc": " We provide legal assistance in civil matters including property disputes, contractual disagreements, and claims for compensation, ensuring the protection of your legal rights through proper legal procedures.",
    s3: "Family Law",
    "s3 desc": "Our services cover sensitive family matters such as divorce, child custody, inheritance, and marital disputes, handled with professionalism, confidentiality, and a focus on fair resolution.",
    s4: "Business Law",
    "s4 desc": "We assist businesses with legal compliance, contract drafting, dispute resolution, and corporate advisory services to ensure lawful and sustainable business operations.",
    s5: "Education Law",
    "s5 desc": " Our expertise includes handling legal issues related to educational institutions, student rights, regulatory compliance, and disputes within the education sector.",
    s6: "Criminal Law",
    "s6 desc": " We provide strong legal representation in criminal matters, safeguarding the rights of individuals through strategic defense and professional advocacy before the courts.",
    //features
    f: "Why Choose Us",
    f1: "Best Law Practices",
    "f1 desc": "Our firm follows the highest standards of legal practice, combining deep legal knowledge with strategic thinking to provide reliable representation. Every case is approached with professionalism, ethical integrity, and a commitment to protecting our clients’ rights.",  
    f2: "Efficiency & Trust",
    "f2 desc": "We prioritize transparent communication, timely legal services, and a trustworthy relationship with our clients. Our approach ensures that every legal matter is handled efficiently while maintaining the highest level of confidentiality and trust.",
    f3: "Results You Deserve",
    "f3 desc": "Our goal is to secure the best possible outcome for every client. Through dedicated advocacy, careful legal analysis, and persistent representation, we strive to deliver results that protect your interests and uphold justice.",
    //team
    t: "Meet Our Expert Attorneys",
    t1: "Padam Bahadur Shrestha",
    "t1 desc": "Advocate | Consultant Lawyer",
    t2: "Bishnu Kumar Thokar",
    "t2 desc": "Advocate | Consultant Lawyer",
    t3: "Satkon Shrestha",
    "t3 desc": "Advocate | Consultant Lawyer",
    t4: "Raju Phuyal",
    "t4 desc": "Advocate | Consultant Lawyer",
    t5: "Shanta Panta",
    "t5 desc": "Advocate | Consultant Lawyer",
    t6: "Joni Mainali",
    "t6 desc": "Advocate | Consultant Lawyer",
    t7: "Hardik Subedi",
    "t7 desc": "Advocate | Consultant Lawyer",
    //footer
    fo1: "Location",
    fo2: "Services Areas",
    "fo2 desc1": "Civil Law",
    "fo2 desc2": "Family Law",
    "fo2 desc3": "Business Law",
    "fo2 desc4": "Education Law",
    "fo2 desc5": "Criminal Law",
    fo3: "Useful Pages",
    "fo3 desc1": "About Us",
    "fo3 desc2": "Practices",
    "fo3 desc3": "Attorneys",
    "fo3 desc4": "Why Choose Us?",
    fo4: "Contact Us",
    "fo4 desc1": "Anamnagar, Kathmandu",
    "fo4 desc2": "+012 345 67890",
    fo5l1: "Environment Law",
    fo5l2: "Personal Legal Matter",
    fo5l3: "Lawyers",
    fo61: "© Environment Law Society Nepal",
    fo62: "All Right Reserved"
  },
  
  ne: {
   // top bar
    time: "बिहान १०:०० - साँझ ५:०० बजे सम्म",
    "opening hours": "खुल्ने समय: आइतबार - शुक्रबार",
    number: "+९७७ १२३४५६७८९",
    "number description": "परामर्शको लागि सम्पर्क गर्नुहोस्",
    // navbar
    home: "गृहपृष्ठ",
    about: "हाम्रो बारेमा",
    practice: "कार्यक्षेत्र",
    attorneys: "अधिवक्ताहरू",
    contact: "सम्पर्क विवरण",
    location: "ठेगाना",
    // carousel
    carousel1: "हामी तपाईंको न्यायको लागि लड्छौं।",
    "carousel1 desc": "न्याय एक निष्पक्ष समाजको आधारशिला हो, जसले कानूनको शासन अन्तर्गत प्रत्येक व्यक्तिले समान संरक्षण, मर्यादा र जवाफदेहिता प्राप्त गर्ने कुरा सुनिश्चित गर्दछ।",
    carousel2: "हामी तपाईंको पक्षमा लड्न तयार छौं।",
    "carousel2 desc": "हाम्रो टोली दृढ संकल्प, रणनीतिक वकालत, र उत्तम नतिजा प्राप्त गर्नका लागि अटुट समर्पणका साथ तपाईंको अधिकारको रक्षा गर्न प्रतिबद्ध छ।",
    carousel3: "हामी तपाईंका विशेष अधिकारहरूको लागि लड्छौं।",
    "carousel3 desc": "हामी तपाईंको कानुनी हितको रक्षा गर्न, इमानदारी, विशेषज्ञता र न्यायप्रतिको दृढ प्रतिबद्धताका साथ तपाईंको अधिकारको वकालत गर्दै अडिग रहन्छौं।",
    //top feature
    feature1: "कानूनी",
    "feature1 desc": "नेपाल सरकारद्वारा स्वीकृत",
    feature2: "अधिवक्ताहरू",
    "feature2 desc": "दक्ष अधिवक्ताहरू",
    feature3: "सफलता",
    "feature3 desc": "मुद्दा जित्ने उच्च दर",
    feature4: "सहयोग",
    "feature4 desc": "द्रुत कानूनी सहायता",
    //about
    a1: "हाम्रो बारेमा जान्नुहोस्",
    "a1 desc1": "वातावरण कानून समाज नेपाल फौजदारी, देवानी, पारिवारिक, शिक्षा, र व्यावसायिक कानून जस्ता विभिन्न कानूनी क्षेत्रहरूमा अधिवक्ता र परामर्शदाता वकिलको रूपमा कार्यरत सात जना समर्पित कानुन व्यवसायीहरूको एउटा समूह हो। हाम्रा प्रत्येक सदस्यको आफ्नै स्वतन्त्र कानुनी अभ्यास भए तापनि, हामी नेपालमा वातावरणीय कानुनको प्रवर्द्धन, वकालत र यसको कार्यान्वयनलाई सुदृढ गर्ने साझा उद्देश्यका साथ वातावरण कानून समाज नेपाल को साझा मञ्चमा सामूहिक रूपमा आबद्ध छौँ।",
    "a1 desc2": "हाम्रो सामूहिक लक्ष्य वातावरणीय न्यायको रक्षा गर्नुका साथै व्यक्ति तथा संस्थाहरूलाई कानुनी सहयोग प्रदान गर्नु हो। सेवाग्राहीहरूले व्यक्तिगत कानूनी मामिलाहरूमा व्यावसायिक कानूनी प्रतिनिधित्व र परामर्शका लागि हामीलाई सम्पर्क गर्न सक्नुहुन्छ, जहाँ हाम्रा अधिवक्ताहरूले कानुनी विज्ञता र नैतिक अभ्यासमा आधारित रहेर लगनशील र सिद्धान्तनिष्ठ सहयोग प्रदान गर्दछन्। व्यक्तिगत तथा संस्थागत कानुनी सेवाभन्दा बाहिर, वातावरण कानुन समाज नेपालले वातावरणीय संरक्षण र दिगो विकासप्रति प्रतिबद्धता साझा गर्ने कानूनी व्यवसायीहरू, संरक्षणविद्हरू, अनुसन्धानकर्ताहरू र अन्तर्राष्ट्रिय साझेदारहरूसँगको सहकार्यलाई हार्दिक स्वागत गर्दछ।",
    "a1 desc3": "थप जान्नुहोस्",
    //service
    s: "हाम्रो कार्यक्षेत्रहरू",
    "s1": "वातावरण कानून",
    "s1 desc": "हामी वातावरण कानूनमा कानूनी विशेषज्ञता प्रदान गर्दछौं, जसमा हामी हाम्रा ग्राहकहरूलाई नियामक अनुपालन, वातावरणीय प्रभाव मूल्याङ्कन, र आगामी पुस्ताका लागि हाम्रो ग्रहको रक्षा गर्न दिगो अभ्यासहरूको वकालत गर्न मद्दत गर्दछौं।",
    "s2": "देवानी कानून",
    "s2 desc": "हामी सम्पत्ति विवाद, सम्झौता सम्बन्धी असहमति, र क्षतिपूर्तिका दाबीहरू लगायतका देवानी मामिलाहरूमा कानूनी सहायता प्रदान गर्दछौं। हामी उचित कानूनी प्रक्रिया मार्फत तपाईंको कानूनी अधिकारको सुरक्षा सुनिश्चित गर्दछौं।",
    "s3": "पारिवारिक कानून",
    "s3 desc": "हाम्रा सेवाहरूले सम्बन्ध विच्छेद, बच्चाको संरक्षण (कस्टडी), अंशबण्डा, र वैवाहिक विवाद जस्ता संवेदनशील पारिवारिक मामिलाहरूलाई समेट्छन्। हामी यी मुद्दाहरूलाई व्यावसायिकता, गोपनीयता, र निष्पक्ष समाधानमा केन्द्रित रहेर समाधान गर्दछौँ।",
    "s4": "व्यावसायिक कानून",
    "s4 desc": "हामी व्यवसायहरूलाई कानूनी अनुपालन, सम्झौताको मस्यौदा (कन्ट्र्याक्ट ड्राफ्टिङ), विवाद समाधान, र कर्पोरेट सल्लाहकार सेवाहरूमा सहयोग पुर्‍याउँछौं। हामी कानूनसम्मत र दिगो व्यावसायिक सञ्चालन सुनिश्चित गर्न प्रतिबद्ध छौं।",
    "s5": "शैक्षिक कानून",
    "s5 desc": "हाम्रो विशेषज्ञतामा शैक्षिक संस्थाहरूसँग सम्बन्धित कानूनी मुद्दाहरू, विद्यार्थीका अधिकारहरू, नियामक अनुपालन, र शिक्षा क्षेत्रभित्रका विवादहरूको व्यवस्थापन समावेश छन्।",
    "s6": "फौजदारी कानून",
    "s6 desc": "हामी फौजदारी मामिलाहरूमा बलियो कानूनी प्रतिनिधित्व प्रदान गर्दछौं। हामी रणनीतिक प्रतिरक्षा र अदालतमा व्यावसायिक वकालत मार्फत व्यक्तिहरूको अधिकारको रक्षा गर्दछौं।",
    //features
    f: "हामीलाई किन रोज्ने?",
    f1: "उत्कृष्ट कानूनी अभ्यास", 
    "f1 desc": "हाम्रो फर्मले कानूनी अभ्यासका उच्च मापदण्डहरू पालना गर्दछ। हामी भरपर्दो प्रतिनिधित्व प्रदान गर्न गहिरो कानूनी ज्ञान र रणनीतिक सोचलाई एकीकृत गर्दछौं। हामी प्रत्येक मुद्दालाई व्यावसायिकता, नैतिक निष्ठा, र हाम्रा ग्राहकहरूको अधिकारको रक्षा गर्ने प्रतिबद्धताका साथ अगाडि बढाउँछौं।",
    f2: "दक्षता र विश्वास",
    "f2 desc": "हामी पारदर्शी सञ्चार, समयमै कानूनी सेवा, र हाम्रा ग्राहकहरूसँग विश्वासिलो सम्बन्धलाई प्राथमिकता दिन्छौं। हाम्रो दृष्टिकोणले प्रत्येक कानूनी मामिलालाई उच्चतम स्तरको गोपनीयता र विश्वास कायम राख्दै कुशलतापूर्वक व्यवस्थापन गर्ने कुरा सुनिश्चित गर्दछ।",
    f3: "हक र अधिकारका लागि",
    "f3 desc": "हाम्रो लक्ष्य प्रत्येक ग्राहकका लागि उत्तम सम्भावित नतिजा सुनिश्चित गर्नु हो। समर्पित वकालत, सावधानीपूर्वक कानूनी विश्लेषण, र निरन्तर प्रतिनिधित्व मार्फत, हामी तपाईंको हितको रक्षा गर्ने र न्याय कायम गर्ने परिणामहरू प्रदान गर्न प्रयास गर्दछौं।",
    //team
    t: "हाम्रा विशेषज्ञ अधिवक्ताहरू",
    t1: "पदम बहादुर श्रेष्ठ",
    "t1 desc": "अधिवक्ता | परामर्शदाता वकील",
    t2: "विष्णु कुमार थोकर",
    "t2 desc": "अधिवक्ता | परामर्शदाता वकील",
    t3: "षटकोण श्रेष्ठ",
    "t3 desc": "अधिवक्ता | परामर्शदाता वकील",
    t4: "राजु फुयाल",
    "t4 desc": "अधिवक्ता | परामर्शदाता वकील",
    t5: "शान्ता पन्त",
    "t5 desc": "अधिवक्ता | परामर्शदाता वकील",
    t6: "जोनी मैनाली",
    "t6 desc": "अधिवक्ता | परामर्शदाता वकील",
    t7: "हार्दिक सुवेदी",
    "t7 desc": "अधिवक्ता | परामर्शदाता वकील",
    //footer
    fo1: "ठेगाना",
    fo2: "सेवा क्षेत्रहरू",
    "fo2 desc1": "देवानी कानून",
    "fo2 desc2": "पारिवारिक कानून",
    "fo2 desc3": "व्यावसायिक कानून",
    "fo2 desc4": "शैक्षिक कानून",
    "fo2 desc5": "फौजदारी कानून",
    fo3: "उपयोगी पृष्ठहरू",
    "fo3 desc1": "हाम्रो बारेमा",
    "fo3 desc2": "सेवाका क्षेत्रहरू",
    "fo3 desc3": "अधिवक्ताहरू",
    "fo3 desc4": "हामीलाई किन रोज्ने?",
    fo4: "सम्पर्क विवरण",
    "fo4 desc1": "अनामनगर, काठमाडौं",
    "fo4 desc2": "+०१२ ३४५ ६७८९०",
    fo5l1: "वातावरण कानून",
    fo5l2: "व्यक्तिगत कानूनी मामिलाहरू",
    fo5l3: "अधिवक्ताहरू",
    fo61: "© वातावरण कानून समाज नेपाल",
    fo62: "सबै अधिकार सुरक्षित"
  }




};

function setLanguage(lang) {
  document.querySelectorAll("[data-key]").forEach(element => {
    const key = element.getAttribute("data-key");
    element.innerText = translations[lang][key];
  });
}

// default language
setLanguage("en");
